#!/bin/sh
shout() { echo "package/upgrade: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }
usage() {
  shout "usage: package/upgrade"
  exit 100
}

ln_command() {
  safe rm -f "$1"'{new}'
  safe ln -s "$2" "$1"'{new}'
  safe mv -f "$1"'{new}' "$1"
}

cp_command() {
  safe rm -f "$1"'{new}'
  safe cp -p "$2" "$1"'{new}'
  safe mv -f "$1"'{new}' "$1"
}

#### MAIN

umask 022
compile="compile"

test -d package || barf "no package directory"
test -d "$compile" || barf "no compile directory"

here="`env - PATH="$PATH" pwd`"

name="`awk '$1{print $1; exit 0}' package/name`"
package="`basename "$name"`"
current="`basename "$here"`"
parent="`dirname "$here"`"

do_man=0
test -f "$compile/man=yes" && do_man=1
do_hier=0
test -f "$compile/hier=yes" && do_hier=1
# only if do_man, or do_hier
#TODO: setup actual support for env variables
hier_prefix="$TRIGGER_PREFIX"
test -z "$hier_prefix" && hier_prefix="/usr/local"
share_path="$TRIGGER_SHARE"
test -z "$share_path" && share_path="share"
trigger_section="$TRIGGER_SECTION"
test -z "$trigger_section" && trigger_section="1"
man_path="$hier_prefix/$share_path/man/man$trigger_section"
bin_path="$hier_prefix/bin"

# Link only if working in versioned directory.
if test "$current" != "$package"
then
  safe rm -f "$package"
  safe ln -s "$current" "$package"
  safe mv -f "$package" ..
fi

# Link non-private commands into other directories.
if test $do_hier -eq 0 -a -r package/command-ln
then
  awk '$1{print $1; next};{exit 0}' package/command-ln | while read d
  do
    safe mkdir -p "$d"
    safe awk '"PRIVATE" != $2 && "" != $1 { print $1 }' package/commands | while read f
    do
      safe ln_command "$d/$f" "$parent/$package/command/$f"
    done
  done
fi

# Copy non-private commands into other directories.
if test $do_hier -eq 1 -o -r package/command-cp
then
  if test $do_hier -eq 1
  then
    echo "$bin_path"
  else
    awk '$1{print $1; next};{exit 0}' < package/command-cp
  fi | while read d
  do
    safe mkdir -p "$d"
    safe awk '"PRIVATE" != $2 && "" != $1 { print $1 }' package/commands | while read f
    do
      safe cp_command "$d/$f" "$parent/$package/command/$f"
    done
  done
fi

# install man pages
if test $do_man -eq 1
then
  safe awk '"PRIVATE" != $2 && "" != $1 { print $1 }' package/commands | while read f
  do
    safe cp_command "$man_path/$f.$trigger_section.gz" "$compile/$f.$trigger_section.gz"
  done
fi

exit 0
